//
//  Copyright (c) SRG SSR. All rights reserved.
//
//  License information is available from the LICENSE file.
//

#import "SRGAlbum.h"
#import "SRGArtist.h"
#import "SRGBaseTopic.h"
#import "SRGBroadcastInformation.h"
#import "SRGChannel.h"
#import "SRGChannelIdentifierMetadata.h"
#import "SRGChapter.h"
#import "SRGContentPage.h"
#import "SRGContentPresentation.h"
#import "SRGContentSection.h"
#import "SRGCrewMember.h"
#import "SRGDataProviderMessages.h"
#import "SRGDay.h"
#import "SRGDRM.h"
#import "SRGEpisode.h"
#import "SRGEpisodeComposition.h"
#import "SRGIdentifierMetadata.h"
#import "SRGImageMetadata.h"
#import "SRGMedia.h"
#import "SRGMediaAggregations.h"
#import "SRGMediaComposition.h"
#import "SRGMediaIdentifierMetadata.h"
#import "SRGMediaMetadata.h"
#import "SRGMediaParentMetadata.h"
#import "SRGMediaSearchSettings.h"
#import "SRGMetadata.h"
#import "SRGModel.h"
#import "SRGModule.h"
#import "SRGModuleIdentifierMetadata.h"
#import "SRGPresenter.h"
#import "SRGProgram.h"
#import "SRGProgramComposition.h"
#import "SRGRelatedContent.h"
#import "SRGResource.h"
#import "SRGScheduledLivestreamMetadata.h"
#import "SRGSearchResult.h"
#import "SRGSearchSuggestion.h"
#import "SRGSection.h"
#import "SRGSegment.h"
#import "SRGServiceMessage.h"
#import "SRGShow.h"
#import "SRGShowAndMedias.h"
#import "SRGShowIdentifierMetadata.h"
#import "SRGShowStatisticsOverview.h"
#import "SRGSocialCount.h"
#import "SRGSocialCountOverview.h"
#import "SRGSong.h"
#import "SRGSubdivision.h"
#import "SRGSubtitle.h"
#import "SRGSubtopic.h"
#import "SRGTopic.h"
#import "SRGTopicIdentifierMetadata.h"
#import "SRGTypes.h"
#import "SRGVariant.h"
